# Pandas

In [114]:
import pandas as pd
import numpy as np

In [115]:
df = pd.DataFrame(np.arange(0, 30).reshape(5,6), index=['Row1', 'Row2', 'Row3', 'Row4', 'Row5'], columns=['Column1', 'Column2', 'Column3', 'Column4', 'Column5', 'Column6'])
# Display the DataFrame
print(df)

      Column1  Column2  Column3  Column4  Column5  Column6
Row1        0        1        2        3        4        5
Row2        6        7        8        9       10       11
Row3       12       13       14       15       16       17
Row4       18       19       20       21       22       23
Row5       24       25       26       27       28       29

In [116]:
df.to_csv('data.csv')

In [117]:
df.loc['Row5']

Column1    24
Column2    25
Column3    26
Column4    27
Column5    28
Column6    29
Name: Row5, dtype: int64

In [118]:
df.iloc[:,:]

      Column1  Column2  Column3  Column4  Column5  Column6
Row1        0        1        2        3        4        5
Row2        6        7        8        9       10       11
Row3       12       13       14       15       16       17
Row4       18       19       20       21       22       23
Row5       24       25       26       27       28       29

In [119]:
df.iloc[3:5, :]

      Column1  Column2  Column3  Column4  Column5  Column6
Row4       18       19       20       21       22       23
Row5       24       25       26       27       28       29

In [120]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
Column5    0
Column6    0
dtype: int64

In [121]:
df = pd.read_csv("csv_data.csv") #reads csv file
df

,First Name,Last Name,School,College,Grade (Intermediate),State
0,Arin,Sharma,St. Vishna RRN School,Mangalayatan University,65%,Uttar Pradesh
1,Advik,Verma,Kendriya Vidyalaya,"National Law University, Delhi",68%,Uttarakhand
2,Vishal,Verma,Kendriya Vidyalaya,National Defence Academy,86%,Uttarakhand
3,Vikas,Singh,Kendriya Vidyalaya,AIIMS (Delhi),88%,Bihar
4,Vaishnavi,Singh,Kendriya Vidyalaya,NIT Kurukshetra,84%,Haryana
5,Rishita,Bhatt,Kendriya Vidyalaya,IIT Roorkee,99.20%,Gujarat

In [122]:
data = pd.read_json("json_data.json") #reads json data
data.head() #lists first 5 data

,id,title,slug,description,price,instructor,isFeatured,image
0,1,Guitar Fundamentals,guitar-fundamentals,Learn the basics of playing guitar with our co...,99.99,John Doe,True,https://images.unsplash.com/photo-152520154086...
1,2,Advanced Jazz Piano,advanced-jazz-piano,"Explore complex chords, improvisation, and jaz...",149.99,Sarah Chen,False,https://images.unsplash.com/photo-1549419615-5...
2,3,Drums: Rhythm Mastery,drums-rhythm-mastery,Techniques for various drumming styles includi...,119.50,Mike Johnson,True,https://images.unsplash.com/photo-1558296245-7...
3,4,Vocal Training for Beginners,vocal-training-beginners,"Improve pitch, breathing control, and vocal ra...",89.00,Aisha Khan,False,https://images.unsplash.com/photo-157777748450...
4,5,Music Production in Ableton,music-production-ableton,"From recording to mixing, master the digital a...",199.99,Alex Rodriguez,True,https://images.unsplash.com/photo-151860013917...

In [123]:
data = pd.read_excel("excel_data.xlsx") #reads excel data
data.tail() #reads last 5 data

,First Name,Last Name,School,College,Grade (Intermediate),State
1,Advik,Verma,Kendriya Vidyalaya,"National Law University, Delhi",0.680,Uttarakhand
2,Vishal,Verma,Kendriya Vidyalaya,National Defence Academy,0.860,Uttarakhand
3,Vikas,Singh,Kendriya Vidyalaya,AIIMS (Delhi),0.880,Bihar
4,Vaishnavi,Singh,Kendriya Vidyalaya,NIT Kurukshetra,0.840,Haryana
5,Rishita,Bhatt,Kendriya Vidyalaya,IIT Roorkee,0.992,Gujarat

In [124]:
#Creating Data
data = {
    "First Name": ["Arin", "Advik", "Vishal", "Vikas", "Radhika", "Vaishnavi", "Rishita"],
    "Last Name": ["Sharma", "Verma", "Verma", "Singh", "Singh", "Singh", "Bhatt"],
    "Age": [21, 20, 20, 20, 20, 20, 21],
    "School": ["St. Vishna RRN School", "Kendriya Vidyalaya", "Kendriya Vidyalaya", "Kendriya Vidyalaya", "Kendriya Vidyalaya", "Kendriya Vidyalaya", "Kendriya Vidyalaya"],
    "Grade (Intermediate)": ["65%", "69%", "86%", "88%", "96%", "84%", "99%" ],
    "State": ["Uttar Pradesh", "Uttarakhand", "Uttarakhand", "Bihar", "Sikkim", "Haryana", "Gujarat"],
    "College": ["Mangalayatan University", "National Law University, Delhi", "National Defence Academy", "AIIMS (Delhi)", "Amity University", "NIT Kurukshetra", "IIT Roorkee"],
    "College Grade": [7.87, 7.9, 8.7, 8.5, 9.1, 8.3, 9.98],
    "Profession": ["Data Scientist", "Advocate", "Army", "Doctor", "Software Engineer", "IAS", "AI Engineer"],
}

In [125]:
df = pd.DataFrame(data) #creating data into dataframe
df

,First Name,Last Name,Age,School,Grade (Intermediate),State,College,College Grade,Profession
0,Arin,Sharma,21,St. Vishna RRN School,65%,Uttar Pradesh,Mangalayatan University,7.87,Data Scientist
1,Advik,Verma,20,Kendriya Vidyalaya,69%,Uttarakhand,"National Law University, Delhi",7.90,Advocate
2,Vishal,Verma,20,Kendriya Vidyalaya,86%,Uttarakhand,National Defence Academy,8.70,Army
3,Vikas,Singh,20,Kendriya Vidyalaya,88%,Bihar,AIIMS (Delhi),8.50,Doctor
4,Radhika,Singh,20,Kendriya Vidyalaya,96%,Sikkim,Amity University,9.10,Software Engineer
5,Vaishnavi,Singh,20,Kendriya Vidyalaya,84%,Haryana,NIT Kurukshetra,8.30,IAS
6,Rishita,Bhatt,21,Kendriya Vidyalaya,99%,Gujarat,IIT Roorkee,9.98,AI Engineer

In [126]:
df[df["Age"] > 20]

,First Name,Last Name,Age,School,Grade (Intermediate),State,College,College Grade,Profession
0,Arin,Sharma,21,St. Vishna RRN School,65%,Uttar Pradesh,Mangalayatan University,7.87,Data Scientist
6,Rishita,Bhatt,21,Kendriya Vidyalaya,99%,Gujarat,IIT Roorkee,9.98,AI Engineer

In [127]:
df.to_csv("data.csv", index=False) #creates data into csv file

In [128]:
df.to_excel("data.xlsx", index=False)  #creates data into excel file

In [129]:
df.to_json("data.json", index=False)  #creates data into json file
df

,First Name,Last Name,Age,School,Grade (Intermediate),State,College,College Grade,Profession
0,Arin,Sharma,21,St. Vishna RRN School,65%,Uttar Pradesh,Mangalayatan University,7.87,Data Scientist
1,Advik,Verma,20,Kendriya Vidyalaya,69%,Uttarakhand,"National Law University, Delhi",7.90,Advocate
2,Vishal,Verma,20,Kendriya Vidyalaya,86%,Uttarakhand,National Defence Academy,8.70,Army
3,Vikas,Singh,20,Kendriya Vidyalaya,88%,Bihar,AIIMS (Delhi),8.50,Doctor
4,Radhika,Singh,20,Kendriya Vidyalaya,96%,Sikkim,Amity University,9.10,Software Engineer
5,Vaishnavi,Singh,20,Kendriya Vidyalaya,84%,Haryana,NIT Kurukshetra,8.30,IAS
6,Rishita,Bhatt,21,Kendriya Vidyalaya,99%,Gujarat,IIT Roorkee,9.98,AI Engineer

In [130]:
df = pd.read_csv("csv_data.csv") #reads csv file

In [131]:
df.head(1) #return first data

,First Name,Last Name,School,College,Grade (Intermediate),State
0,Arin,Sharma,St. Vishna RRN School,Mangalayatan University,65%,Uttar Pradesh

In [132]:
df.tail(1) #return last data

,First Name,Last Name,School,College,Grade (Intermediate),State
5,Rishita,Bhatt,Kendriya Vidyalaya,IIT Roorkee,99.20%,Gujarat

In [133]:
df.info() #returns data summary

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   First Name            6 non-null      object
 1   Last Name             6 non-null      object
 2   School                6 non-null      object
 3   College               6 non-null      object
 4   Grade (Intermediate)  6 non-null      object
 5   State                 6 non-null      object
dtypes: object(6)
memory usage: 420.0+ bytes

In [134]:
df.describe()

,First Name,Last Name,School,College,Grade (Intermediate),State
count,6,6,6,6,6,6
unique,6,4,2,6,6,5
top,Arin,Verma,Kendriya Vidyalaya,Mangalayatan University,65%,Uttarakhand
freq,1,2,5,1,1,2

In [135]:
#Creating Data
data = {
    "Name": ["Arin", "Rishita", "Vaishnavi", "Advik", "Vishal", "Radhika"],
    "Grade": [65, 99, 84, 68, 86, 88],
    "State": ["Uttar Pradesh", "Gujarat", "Haryana","Uttarakhand", "Uttarakhand", "Madhya Pradesh"],
    "Gender": ["Male", "Female", "Female", "Male","Male", "Female"],
    "Salary": [60000, 950000, 40000, 20000, 10000, 65000]
}
df = pd.DataFrame(data)
df

        Name  Grade           State  Gender  Salary
0       Arin     65   Uttar Pradesh    Male   60000
1    Rishita     99         Gujarat  Female  950000
2  Vaishnavi     84         Haryana  Female   40000
3      Advik     68     Uttarakhand    Male   20000
4     Vishal     86     Uttarakhand    Male   10000
5    Radhika     88  Madhya Pradesh  Female   65000

In [136]:
df.describe() # generate descriptive statistics of a dataFrame

           Grade         Salary
count   6.000000       6.000000
mean   81.666667  190833.333333
std    12.878923  372537.470151
min    65.000000   10000.000000
25%    72.000000   25000.000000
50%    85.000000   50000.000000
75%    87.500000   63750.000000
max    99.000000  950000.000000

#### Knowing column and shape of dataset

In [137]:
df.shape #returns shape

(6, 5)

In [138]:
df.columns #returns columns

Index(['Name', 'Grade', 'State', 'Gender', 'Salary'], dtype='object')

#### Filtering based on condition

In [139]:
salary = df[df["Salary"]> 50000]
salary

      Name  Grade           State  Gender  Salary
0     Arin     65   Uttar Pradesh    Male   60000
1  Rishita     99         Gujarat  Female  950000
5  Radhika     88  Madhya Pradesh  Female   65000

In [140]:
lower_salary = df[(df["Salary"] > 10000) & (df["Salary"] < 50000)]
lower_salary

        Name  Grade        State  Gender  Salary
2  Vaishnavi     84      Haryana  Female   40000
3      Advik     68  Uttarakhand    Male   20000

In [141]:
df["Name"] #returns single column

0         Arin
1      Rishita
2    Vaishnavi
3        Advik
4       Vishal
5      Radhika
Name: Name, dtype: object

In [142]:
df[["Name", "Salary"]] #returns multiple columns

        Name  Salary
0       Arin   60000
1    Rishita  950000
2  Vaishnavi   40000
3      Advik   20000
4     Vishal   10000
5    Radhika   65000

In [143]:
higher_rankers = df[(df["Grade"] > 85) & (df["Grade"] < 90)]
higher_rankers

      Name  Grade           State  Gender  Salary
4   Vishal     86     Uttarakhand    Male   10000
5  Radhika     88  Madhya Pradesh  Female   65000

In [144]:
passed = df[(df["Grade"] > 50) & (df["Grade"] < 70)]
passed

    Name  Grade          State Gender  Salary
0   Arin     65  Uttar Pradesh   Male   60000
3  Advik     68    Uttarakhand   Male   20000

In [145]:
df

        Name  Grade           State  Gender  Salary
0       Arin     65   Uttar Pradesh    Male   60000
1    Rishita     99         Gujarat  Female  950000
2  Vaishnavi     84         Haryana  Female   40000
3      Advik     68     Uttarakhand    Male   20000
4     Vishal     86     Uttarakhand    Male   10000
5    Radhika     88  Madhya Pradesh  Female   65000

In [146]:
successfull = df[(df["Grade"] > 70) | (df["Salary"] > 15000)]
successfull

        Name  Grade           State  Gender  Salary
0       Arin     65   Uttar Pradesh    Male   60000
1    Rishita     99         Gujarat  Female  950000
2  Vaishnavi     84         Haryana  Female   40000
3      Advik     68     Uttarakhand    Male   20000
4     Vishal     86     Uttarakhand    Male   10000
5    Radhika     88  Madhya Pradesh  Female   65000

In [147]:
#Creating Data
data = {
    "Name": ["Arin", "Rishita", "Vaishnavi", "Advik", "Vishal", "Radhika"],
    "Grade": [65, 99, 84, 68, 86, 88],
    "State": ["Uttar Pradesh", "Gujarat", "Haryana","Uttarakhand", "Uttarakhand", "Madhya Pradesh"],
    "Gender": ["Male", "Female", "Female", "Male","Male", "Female"],
    "Salary": [60000, 950000, 40000, 20000, 10000, 65000]
}
df = pd.DataFrame(data)
df

        Name  Grade           State  Gender  Salary
0       Arin     65   Uttar Pradesh    Male   60000
1    Rishita     99         Gujarat  Female  950000
2  Vaishnavi     84         Haryana  Female   40000
3      Advik     68     Uttarakhand    Male   20000
4     Vishal     86     Uttarakhand    Male   10000
5    Radhika     88  Madhya Pradesh  Female   65000

In [148]:
df["Bonus"] = df['Salary'] * 0.1 #added column Bonus
df

        Name  Grade           State  Gender  Salary    Bonus
0       Arin     65   Uttar Pradesh    Male   60000   6000.0
1    Rishita     99         Gujarat  Female  950000  95000.0
2  Vaishnavi     84         Haryana  Female   40000   4000.0
3      Advik     68     Uttarakhand    Male   20000   2000.0
4     Vishal     86     Uttarakhand    Male   10000   1000.0
5    Radhika     88  Madhya Pradesh  Female   65000   6500.0

In [149]:
#df.insert(location, column-name, data)
df.insert(0, "ID Number", [25, 27, 18, 22, 21, 31])
df

   ID Number       Name  Grade           State  Gender  Salary    Bonus
0         25       Arin     65   Uttar Pradesh    Male   60000   6000.0
1         27    Rishita     99         Gujarat  Female  950000  95000.0
2         18  Vaishnavi     84         Haryana  Female   40000   4000.0
3         22      Advik     68     Uttarakhand    Male   20000   2000.0
4         21     Vishal     86     Uttarakhand    Male   10000   1000.0
5         31    Radhika     88  Madhya Pradesh  Female   65000   6500.0

In [150]:
#update a column value
df.loc[0, "Salary"] = 90000
df

   ID Number       Name  Grade           State  Gender  Salary    Bonus
0         25       Arin     65   Uttar Pradesh    Male   90000   6000.0
1         27    Rishita     99         Gujarat  Female  950000  95000.0
2         18  Vaishnavi     84         Haryana  Female   40000   4000.0
3         22      Advik     68     Uttarakhand    Male   20000   2000.0
4         21     Vishal     86     Uttarakhand    Male   10000   1000.0
5         31    Radhika     88  Madhya Pradesh  Female   65000   6500.0

In [151]:
#increase salary by 5%
df['Salary'] = df['Salary'] * 1.05
df

   ID Number       Name  Grade           State  Gender    Salary    Bonus
0         25       Arin     65   Uttar Pradesh    Male   94500.0   6000.0
1         27    Rishita     99         Gujarat  Female  997500.0  95000.0
2         18  Vaishnavi     84         Haryana  Female   42000.0   4000.0
3         22      Advik     68     Uttarakhand    Male   21000.0   2000.0
4         21     Vishal     86     Uttarakhand    Male   10500.0   1000.0
5         31    Radhika     88  Madhya Pradesh  Female   68250.0   6500.0

In [152]:
#To drop a column
df.drop('Bonus', axis=1, inplace=True)
print(df)

   ID Number       Name  Grade           State  Gender    Salary
0         25       Arin     65   Uttar Pradesh    Male   94500.0
1         27    Rishita     99         Gujarat  Female  997500.0
2         18  Vaishnavi     84         Haryana  Female   42000.0
3         22      Advik     68     Uttarakhand    Male   21000.0
4         21     Vishal     86     Uttarakhand    Male   10500.0
5         31    Radhika     88  Madhya Pradesh  Female   68250.0

## Handling Missing data

In [172]:
#Creating Data
data = {
    "Name": ["Arin", "Rishita", "Vaishnavi", "Advik", "Vishal", "Radhika"],
    "Grade": [None, 99, 84, 68, 86, 88],
    "State": ["Uttar Pradesh", None, "Haryana","Uttarakhand", "Uttarakhand", "Madhya Pradesh"],
    "Gender": ["Male", "Female", None, "Male","Male", "Female"],
    "Salary": [60000, 950000, 40000, None, 10000, 65000]
}
df = pd.DataFrame(data)
df

        Name  Grade           State  Gender    Salary
0       Arin    NaN   Uttar Pradesh    Male   60000.0
1    Rishita   99.0            None  Female  950000.0
2  Vaishnavi   84.0         Haryana    None   40000.0
3      Advik   68.0     Uttarakhand    Male       NaN
4     Vishal   86.0     Uttarakhand    Male   10000.0
5    Radhika   88.0  Madhya Pradesh  Female   65000.0

In [173]:
df.isnull() #return true if value is missing

    Name  Grade  State  Gender  Salary
0  False   True  False   False   False
1  False  False   True   False   False
2  False  False  False    True   False
3  False  False  False   False    True
4  False  False  False   False   False
5  False  False  False   False   False

In [174]:
df.isnull().sum() #return count of value if it is missing

Name      0
Grade     1
State     1
Gender    1
Salary    1
dtype: int64

In [175]:
#update missing with zero
df.fillna(0, inplace=True)
df

        Name  Grade           State  Gender    Salary
0       Arin    0.0   Uttar Pradesh    Male   60000.0
1    Rishita   99.0               0  Female  950000.0
2  Vaishnavi   84.0         Haryana       0   40000.0
3      Advik   68.0     Uttarakhand    Male       0.0
4     Vishal   86.0     Uttarakhand    Male   10000.0
5    Radhika   88.0  Madhya Pradesh  Female   65000.0

In [176]:
#Remove if data is missing
df.dropna(axis=1, inplace=True)
df

        Name  Grade           State  Gender    Salary
0       Arin    0.0   Uttar Pradesh    Male   60000.0
1    Rishita   99.0               0  Female  950000.0
2  Vaishnavi   84.0         Haryana       0   40000.0
3      Advik   68.0     Uttarakhand    Male       0.0
4     Vishal   86.0     Uttarakhand    Male   10000.0
5    Radhika   88.0  Madhya Pradesh  Female   65000.0

## Sorting & aggregation

In [177]:
#Creating Data
data = {
    "Name": ["Arin", "Rishita", "Vaishnavi", "Advik", "Vishal", "Radhika"],
    "Grade": [65, 99, 84, 68, 86, 88],
    "State": ["Uttar Pradesh", "Gujarat", "Haryana","Uttarakhand", "Uttarakhand", "Madhya Pradesh"],
    "Gender": ["Male", "Female", "Female", "Male","Male", "Female"],
    "Salary": [60000, 950000, 40000, 20000, 10000, 65000]
}
df = pd.DataFrame(data)
df

        Name  Grade           State  Gender  Salary
0       Arin     65   Uttar Pradesh    Male   60000
1    Rishita     99         Gujarat  Female  950000
2  Vaishnavi     84         Haryana  Female   40000
3      Advik     68     Uttarakhand    Male   20000
4     Vishal     86     Uttarakhand    Male   10000
5    Radhika     88  Madhya Pradesh  Female   65000

In [178]:
#sorted in descending based on grade
df.sort_values(by="Grade", ascending=False, inplace=True)
df

        Name  Grade           State  Gender  Salary
1    Rishita     99         Gujarat  Female  950000
5    Radhika     88  Madhya Pradesh  Female   65000
4     Vishal     86     Uttarakhand    Male   10000
2  Vaishnavi     84         Haryana  Female   40000
3      Advik     68     Uttarakhand    Male   20000
0       Arin     65   Uttar Pradesh    Male   60000

In [179]:
#sorted in ascending based on grade
df.sort_values(by="Grade", ascending=True, inplace=True)
df

        Name  Grade           State  Gender  Salary
0       Arin     65   Uttar Pradesh    Male   60000
3      Advik     68     Uttarakhand    Male   20000
2  Vaishnavi     84         Haryana  Female   40000
4     Vishal     86     Uttarakhand    Male   10000
5    Radhika     88  Madhya Pradesh  Female   65000
1    Rishita     99         Gujarat  Female  950000

In [180]:
average_salary = df['Salary'].mean()
average_salary

np.float64(190833.33333333334)

In [181]:
grouped = df.groupby("Grade")['Salary'].sum()
grouped

Grade
65     60000
68     20000
84     40000
86     10000
88     65000
99    950000
Name: Salary, dtype: int64

In [182]:
grouped = df.groupby(["Grade", "Name"])['Salary'].sum()
grouped

Grade  Name
65     Arin          60000
68     Advik         20000
84     Vaishnavi     40000
86     Vishal        10000
88     Radhika       65000
99     Rishita      950000
Name: Salary, dtype: int64

## Merging and Concatenation

In [183]:
customers = pd.DataFrame({
    "CustomerID": [1, 2, 3, 4],
    "Name": ["Ram", "Raju", "Mohan", "Shiv"]
})

In [184]:
orders = pd.DataFrame({
    "CustomerID":[1, 2, 3, 4],
    "Amount": [250, 500, 750, 100]
})

In [185]:
merged_df = pd.merge(customers, orders, on="CustomerID", how="inner")
merged_df

   CustomerID   Name  Amount
0           1    Ram     250
1           2   Raju     500
2           3  Mohan     750
3           4   Shiv     100

In [186]:
merged_df = pd.merge(customers, orders, on="CustomerID", how="left")
merged_df

   CustomerID   Name  Amount
0           1    Ram     250
1           2   Raju     500
2           3  Mohan     750
3           4   Shiv     100

In [187]:
customers_df1 = pd.DataFrame({
    "CustomerID": [1, 2, 3],
    "Name": ["Ram", "Narayan", "Shiv"]
})

In [188]:
customers_df2 = pd.DataFrame({
    "CustomerID": [5, 6, 7],
    "Name": ["Sita", "Lakshmi", "Parvati"]
})

In [189]:
#vertically
concatenate = pd.concat([customers_df1, customers_df2], ignore_index=True)
concatenate

   CustomerID     Name
0           1      Ram
1           2  Narayan
2           3     Shiv
3           5     Sita
4           6  Lakshmi
5           7  Parvati

In [190]:
#horizontally
concatenate = pd.concat([customers_df1, customers_df2], axis=1, ignore_index=True)
concatenate

   0        1  2        3
0  1      Ram  5     Sita
1  2  Narayan  6  Lakshmi
2  3     Shiv  7  Parvati